apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: allow-dns-egress-only
  namespace: seba
  annotations:
    k8s.v1.cni.cncf.io/policy-for: sriov-network-1-vlan
spec:
  podSelector:
    matchLabels:
      app: kernel-server
  policyTypes:
    - Ingress
    - Egress
  ingress: [ ]
  egress:
    - to:
        - namespaceSelector: { }
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
---
apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: deny-by-default
  namespace: seba
  annotations:
    k8s.v1.cni.cncf.io/policy-for: sriov-network-1-vlan
spec:
  podSelector:
    matchLabels:
      app: kernel-server
  policyTypes:
    - Ingress
  ingress: []