apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge
  namespace: seba
spec:
  config: '{
    "cniVersion": "0.4.0",
    "name": "mynet",
    "plugins": [
      {
        "type": "bridge",
        "bridge": "mynet0",
        "isDefaultGateway": false,
        "forceAddress": false,
        "ipMasq": true,
        "hairpinMode": true,
        "ipam": {
          "type": "host-local",
          "subnet": "10.10.0.0/16"
        }
      },
      {
        "type":"tuning",
        "capabilities":{
          "mac":true
        },
        "sysctl":{
          "net.ipv6.conf.all.disable_ipv6":"1",
          "net.ipv6.conf.all.accept_ra":"1",
          "net.ipv6.conf.all.autoconf":"1",
          "net.ipv4.conf.all.arp_accept":"1",
          "net.ipv4.conf.all.rp_filter":"1",
          "net.ipv6.conf.default.disable_ipv6":"1",
          "net.ipv6.conf.default.accept_ra":"1",
          "net.ipv6.conf.default.autoconf":"1",
          "net.ipv4.conf.default.arp_accept":"1",
          "net.ipv4.conf.default.rp_filter":"1"
        }
      }
    ]
  }'
