apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: sriov-nic-1
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  nicSelector:
    pfNames: ["ens3f0#5-9"]
  nodeSelector:
    kubernetes.io/hostname: cnfdt4.lab.eng.tlv2.redhat.com
  numVfs: 10
  priority: 99
  resourceName: sriov_nic_1
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: dpdk-nic-1
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  needVhostNet: true
  nicSelector:
    pfNames: ["ens3f0#0-4"]
  nodeSelector:
    kubernetes.io/hostname: cnfdt4.lab.eng.tlv2.redhat.com
  numVfs: 10
  priority: 99
  resourceName: dpdk_nic_1
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: sriov-nic-2
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  nicSelector:
    pfNames: ["ens2f0#5-9"]
  nodeSelector:
    kubernetes.io/hostname: cnfdt4.lab.eng.tlv2.redhat.com
  numVfs: 10
  priority: 99
  resourceName: sriov_nic_2
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: dpdk-network-1
  namespace: openshift-sriov-network-operator
spec:
  ipam: '{"type": "host-local","ranges": [[{"subnet": "10.0.1.0/24"}]],"dataDir":
    "/run/my-orchestrator/container-ipam-state-1"}'
  networkNamespace: seba
  spoofChk: "on"
  trust: "on"
  resourceName: dpdk_nic_1

---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-network-1
  namespace: openshift-sriov-network-operator
spec:
  ipam: '{"type": "host-local","ranges": [[{"subnet": "10.0.2.0/24"}]],"dataDir":
    "/run/my-orchestrator/container-ipam-state-2"}'
  networkNamespace: seba
  spoofChk: "on"
  trust: "on"
  resourceName: sriov_nic_1
#  metaPlugins: |
#    {
#      "type":"tuning",
#      "sysctl":{
#        "net.ipv6.conf.all.disable_ipv6":"1",
#        "net.ipv6.conf.all.accept_ra":"1",
#        "net.ipv6.conf.all.autoconf":"1",
#        "net.ipv4.conf.all.arp_accept":"1",
#        "net.ipv4.conf.all.rp_filter":"1",
#        "net.ipv6.conf.default.disable_ipv6":"1",
#        "net.ipv6.conf.default.accept_ra":"1",
#        "net.ipv6.conf.default.autoconf":"1",
#        "net.ipv4.conf.default.arp_accept":"1",
#        "net.ipv4.conf.default.rp_filter":"1"
#      }
#    }
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-network-2
  namespace: openshift-sriov-network-operator
spec:
  ipam: '{"type": "host-local","ranges": [[{"subnet": "10.0.3.0/24"}]],"dataDir":
    "/run/my-orchestrator/container-ipam-state-3"}'
  networkNamespace: seba
  spoofChk: "on"
  trust: "on"
  resourceName: sriov_nic_2

