---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 02-worker-disable-interface-alt-name
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,L3RtcC8xCg==
          mode: 420
          overwrite: true
          path: /etc/systemd/system.conf.d/disable-alt-name.conf