apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
spec:
  globallyDisableIrqLoadBalancing: true
  cpu:
    isolated: "6-11"
    reserved: 0,2,1,3
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - count: 1
        size: 1G
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  numa:
    topologyPolicy: restricted
  realTimeKernel:
    enabled: false
