---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
       "name": "dpdk-network-1-vlan",
       "mac": "70:00:00:00:00:03",
       "namespace": "seba"
      },
      {
       "name": "dpdk-network-2",
       "mac": "70:00:00:00:00:04",
       "namespace": "seba"
      }
    ]'
    cpu-load-balancing.crio.io: "true"
  labels:
    app: ovs-dpdk
  name: ovs-dpdk
  namespace: seba
spec:
  runtimeClassName: performance-performance
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - trex
          topologyKey: kubernetes.io/hostname
  containers:
    - command:
        - /bin/bash
        - -c
        - /opt/scripts/run-ovs.sh
      image: quay.io/schseba/ovs-dpdk:latest
      imagePullPolicy: Always
      name: ovs-dpdk
      resources:
        limits:
          cpu: "8"
          hugepages-1Gi: 4Gi
          memory: 2Gi
        requests:
          cpu: "8"
          hugepages-1Gi: 4Gi
          memory: 2Gi
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
      volumeMounts:
        - mountPath: /mnt/huge
          name: hugepages
  terminationGracePeriodSeconds: 5
  volumes:
    - emptyDir:
        medium: HugePages
      name: hugepages