---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
       "name": "dpdk-network-1",
       "mac": "50:00:00:00:00:01",
       "namespace": "seba"
      },
      {
       "name": "tap",
       "namespace": "seba",
       "interface": "ext0"
      },
      {
       "name": "tap",
       "namespace": "seba",
       "interface": "ext1"
      },
      {
       "name": "ipvlan-101",
       "namespace": "seba",
       "interface": "ext0.101"
      },
      {
       "name": "ipvlan-102",
       "namespace": "seba",
       "interface": "ext1.102"
      }
    ]'
    cpu-load-balancing.crio.io: "true"
  labels:
    app: dpdk
  name: toolbox
  namespace: seba
spec:
  #  hostNetwork: true
  runtimeClassName: performance-performance
  securityContext:
    fsGroup: 2002
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - trex
          topologyKey: kubernetes.io/hostname
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep INF
      image: quay.io/schseba/dpdk:rhel
#      image: quay.io/schseba/toolbox:latest
      imagePullPolicy: Always
      name: dpdk
      resources:
        limits:
          cpu: "16"
          hugepages-1Gi: 8Gi
          memory: 2Gi
        requests:
          cpu: "16"
          hugepages-1Gi: 8Gi
          memory: 2Gi
      securityContext:
        #        privileged: true
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW #for mlx only
            - NET_ADMIN
#        runAsUser: 0 #for root container
        runAsUser: 1001
        runAsGroup: 2001
      volumeMounts:
        - mountPath: /mnt/huge
          name: hugepages
  terminationGracePeriodSeconds: 2
  volumes:
    - emptyDir:
        medium: HugePages
      name: hugepages