---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
       "name": "sriov-network-2",
       "ips": ["10.0.5.41"],
       "mac": "60:00:00:00:00:01",
       "namespace": "seba"
      },
      {
       "name": "sriov-network-2",
       "ips": ["10.0.5.42"],
       "mac": "60:00:00:00:00:05",
       "namespace": "seba"
      },
      {
       "name": "sriov-network-2",
       "ips": ["10.0.5.43"],
       "mac": "60:00:00:00:00:03",
       "namespace": "seba"
      },
      {
       "name": "sriov-network-2",
       "ips": ["10.0.5.44"],
       "mac": "60:00:00:00:00:04",
       "namespace": "seba"
      },
      {
       "name": "sriov-network-2",
       "ips": ["10.0.5.45"],
       "mac": "60:00:00:00:00:06",
       "namespace": "seba"
      }
    ]'
    cpu-load-balancing.crio.io: "true"
  labels:
    app: kernel-client
  name: client1
  namespace: seba
spec:
  nodeName: cnfdt04.lab.eng.tlv2.redhat.com
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - kernel-server
          topologyKey: kubernetes.io/hostname
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep INF
      image: quay.io/openshift-kni/cnf-tests:latest
      imagePullPolicy: Always
      name: kernel
      securityContext:
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
  terminationGracePeriodSeconds: 1
