---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
       "name": "dpdk-network-1",
       "namespace": "seba"
      }
    ]'
    cpu-load-balancing.crio.io: "true"
  labels:
    app: kernel-server
  name: server
  namespace: seba
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - kernel-client
          topologyKey: kubernetes.io/hostname
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep INF
      image: quay.io/openshift-kni/cnf-tests:latest
      imagePullPolicy: Always
      name: kernel
      securityContext:
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
  terminationGracePeriodSeconds: 5
